---
title: "Relatório Temas para a Saúde"
format: html
editor: visual
---


```{r}
options(scipen = 999)
library(pacman)
p_load(readxl, openxlsx, tidyverse, dplyr, reshape2, kableExtra)
```

```{r}
temas <- read_excel("Temas para Saúde.xlsx", sheet = 1)
anos_1 <- read_excel("Temas para Saúde.xlsx", sheet = 2)
anos_2 <- read_excel("Temas para Saúde.xlsx", sheet = 3)
```

```{r}
anos <- left_join(anos_1, select(anos_2, c(2,4,5,6,7)), by = "Ibge")
anos[is.na(anos)] <- 0
kable(head(anos))
```

```{r}
melted_anos <- (melt(anos, id = c("Uf", "Ibge", "Municipio"), variable.name = "Ano", value.name = "Populacao"))
```

```{r}
temas$Ibge <- as.numeric(temas$Ibge)
temas$Ano <- as.factor(temas$Ano)
temas_atualizado <- left_join(temas, select(melted_anos, c(2,4,5)), by = c("Ibge", "Ano"))
kable(head(temas_atualizado))
```

```{r}
temas_atualizado <- temas_atualizado %>% 
  mutate(Regiao = case_when(
    Uf %in% c("AP", "AM", "RR", "PA", "TO", "RO", "AC") ~ "Norte",
    Uf %in% c("MA", "PI", "CE", "RN", "PE", "PB", "SE", "AL", "BA") ~ "Nordeste",
    Uf %in% c("DF", "MT", "MS", "GO") ~ "Centro-oeste",
    Uf %in% c("SP", "RJ", "ES", "MG") ~ "Sudeste",
    Uf %in% c("SC", "RS", "PR") ~ "Sul"
  ))
```

# Indicadores

```{r}
banco <- temas_atualizado %>% 
  mutate_at(c(5:19), as.numeric)  
```

```{r}
colnames(banco)[8] <- "Ações de combate ao Aedes aegy"
```

De acordo com os dados disponíveis, calcularemos os 15 indicadores para cada observação do banco (`r count(banco)` observações), totalizando então `r 15*count(banco)` indicadores.


```{r}
banco %>% 
  mutate(
    agravo_indicador = `Agravos negligenciados`/Populacao,
    alimentacao_indicador = `Alimentação saudável`/Populacao,
    autocuidado_indicador = `Autocuidado de pessoas com doe`/Populacao,
    acoes_indicador = `Ações de combate ao Aedes aegy`/Populacao,
    cidadania_indicador = `Cidadania e direitos humanos`/Populacao,
    dependencia_indicador = `Dependência química / tabaco /`/Populacao,
    envelhecimento_indicador = `Envelhecimento / Climatério /`/Populacao,
    plantas_indicador = `Plantas medicinais / fitoterap`/Populacao,
    prevencao_indicador = `Prevenção da violência e promo`/Populacao,
    ambiental_indicador = `Saúde ambiental`/Populacao,
    bucal_indicador = `Saúde bucal`/Populacao,
    trabalhador_indicador = `Saúde do trabalhador`/Populacao,
    mental_indicador = `Saúde mental`/Populacao,
    sexual_indicador = `Saúde sexual e reprodutiva`/Populacao,
    semana_saude_indicador = `Semana saúde na escola`/Populacao
    
    ) -> banco
```

```{r}
indicadores <- select(banco, c(1:4, 21:36))
kable(head(indicadores))
```

```{r}
abas <- list("sheet1" = temas_atualizado, "sheet2" = indicadores)
write.xlsx (abas, "temas_para_saude.xlsx")

```
